config/routes.rb
Rails.application.routes.draw do
  resources :attrs

  resources :exercises

end

app/models/attr.rb
class Attr < ActiveRecord::Base
  has_many :exercises
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :attr
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attrs_controller.rb
class AttrsController < ApplicationController
  before_action :set_attr, only: [:show, :edit, :update, :destroy]

  # GET /attrs
  # GET /attrs.json
  def index
    @attrs = Attr.all
  end

  # GET /attrs/1
  # GET /attrs/1.json
  def show
  end

  # GET /attrs/new
  def new
    @attr = Attr.new
  end

  # GET /attrs/1/edit
  def edit
  end

  # POST /attrs
  # POST /attrs.json
  def create
    @attr = Attr.new(attr_params)

    respond_to do |format|
      if @attr.save
        format.html { redirect_to attrs_path, notice: 'Attr was successfully created.' }
        format.json { render :show, status: :created, location: @attr }
      else
        format.html { render :new }
        format.json { render json: @attr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attrs/1
  # PATCH/PUT /attrs/1.json
  def update
    respond_to do |format|
      if @attr.update(attr_params)
        format.html { redirect_to @attr, notice: 'Attr was successfully updated.' }
        format.json { render :show, status: :ok, location: @attr }
      else
        format.html { render :edit }
        format.json { render json: @attr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attrs/1
  # DELETE /attrs/1.json
  def destroy
    @attr.destroy
    respond_to do |format|
      format.html { redirect_to attrs_url, notice: 'Attr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attr
      @attr = Attr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attr_params
      params.require(:attr).permit(:name)
    end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to exercises_path, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:description, :duration, :attr_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attrs_helper.rb
module AttrsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/attrs/_form.html.erb
<%= form_for(@attr) do |f| %>
  <% if @attr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attr.errors.count, "error") %> prohibited this attr from being saved:</h2>

      <ul>
      <% @attr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attrs/edit.html.erb
<h1>Editing attr</h1>

<%= render 'form' %>

<%= link_to 'Show', @attr %> |
<%= link_to 'Back', attrs_path %>

app/views/attrs/index.html.erb
<h1>Listing attrs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attrs.each do |attr| %>
      <tr>
        <td><%= attr.name %></td>
        <td><%= link_to 'Edit', edit_attr_path(attr) %></td>
        <td><%= link_to 'Destroy', attr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attr', new_attr_path %>

app/views/attrs/new.html.erb
<h1>New attr</h1>

<%= render 'form' %>

<%= link_to 'Back', attrs_path %>

app/views/attrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attr.name %>
</p>

<%= link_to 'Edit', edit_attr_path(@attr) %> |
<%= link_to 'Back', attrs_path %>

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :attr_id %><br>
    <%= f.collection_select(:attr_id, Attr.order(:name), :id, :name, include_blank: true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Listing exercises</h1>

<table width="90%" cellspacing = >
  <thead>
    <tr>
      <th>Description</th>
      <th>Attr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>

      <tr>
        <td><%= exercise.description %></td>
        <td><%= exercise.attr ? exercise.attr.name : nil %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>     
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @exercise.description %>
</p>

<p>
  <strong>Attr:</strong>
  <%= @exercise.attr_id %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Climb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>